### ISSUE TITLE
Install issue with en-core-web-sm==2.1.0

### ISSUE THREAD

**Issue by edenprairie** [ddemszky/textbook-analysis#1]
Trying to following instruction to run locally on Windows 10 system but got following error when run
```
pip install -r requirements.txt
```
Could you help? 

ERROR: Could not find a version that satisfies the requirement en-core-web-sm==2.1.0
ERROR: No matching distribution found for en-core-web-sm==2.1.0

![image](https://user-images.githubusercontent.com/24532787/101926027-41cdb480-3b98-11eb-90d8-321f4f5f5360.png)

**Comment by JonnyPillar** [comment]
Hey @edenprairie I just had a similar issue. 
Fixed it by running 

`pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz --no-deps`

then

`pip install -r requirements.txt`

**Comment by Shivam7089** [comment]
> Hey @edenprairie I just had a similar issue. Fixed it by running
> 
> `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz --no-deps`
> 
> then
> 
> `pip install -r requirements.txt`

still getting the same error
![Screenshot (18)](https://github.com/EduNLP/textbook-analysis/assets/99729437/6eb9d35c-e81a-41e9-8dbe-5ddc6f81d8af)
kindly suggest how to resolve it asap
